# Generated by Django 5.1 on 2024-08-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userPassword',
            field=models.CharField(default='pass', max_length=1000),
            preserve_default=False,
        ),
    ]
