# Generated by Django 5.1 on 2024-08-15 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_user_inv_user_money'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Player',
        ),
    ]
